### PR TITLE
Clearify documentation

### PR DESCRIPTION
**Pull request by powtac**

### CODE REVIEW

**Comment by lorenzos** [comment]
Unfortunately this will not be true for the next version of Firefox, 55, out in six days, in which they switched to a new console. The Server messages filter has been removed, and nothing from ChromePhp is displayed.

A **[bug exists](https://bugzilla.mozilla.org/show_bug.cgi?id=1307889)** about that, but it has just been lowered from [priority](https://wiki.mozilla.org/Bugzilla:Priority_System) P3 to P4:

> **P3** = This isn't a bad idea, and maybe we'll want to implement it at some point in the future, but it's not near-term roadmap material. Some core Bugzilla developer may work on it.
> **P4** = This isn't a terrible idea, but it's not important to our long-term plans for Bugzilla. We would review a patch if somebody posted it, but a core developer is unlikely to work on it. If the patch proves to be too complex, there's a chance that the feature will be marked WONTFIX or delayed until some unknown future release.

Maybe it's time to start thinking of a Firefox port of [ccampbell/chromelogger](https://github.com/ccampbell/chromelogger/)?

**Comment by ErikKrause** [comment]
Well, bad news. However, this was only meant as a hack until https://github.com/firephp/firephp-for-firefox-devtools is ready. Just one more reason to press Christoph Dorn to release something...

**Comment by ErikKrause** [comment]
@lorenzos: I just tried in FF 55.0b14 developer edition, and ChromePHP works flawlessly. Be sure to enable all points in the Server droplist separately.

**Comment by lorenzos** [comment]
@ErikKrause You're right, I just tried the 55 beta now! I swear the new console was there two months ago when I tried the 55 (which at the time was in the nightly channel, not in beta), and ChromePhp didn't work :smile: You can still see what I saw if you try the [57 nightly](https://www.mozilla.org/it/firefox/channel/desktop/#nightly) now. Maybe they just postponed that change.

**Pull request merged**
